services:
  - type: web
    name: pos-pc-app
    env: php
    plan: free
    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_NAME
        value: POS_PC
      - key: APP_DEBUG
        value: "false"
      - key: APP_ENV
        value: production
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: pos-pc-db
          property: host
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: pos_pc
      - key: DB_USERNAME
        fromDatabase:
          name: pos-pc-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: pos-pc-db
          property: password
      - key: REDIS_HOST
        fromService:
          name: pos-pc-redis
          property: host
      - key: REDIS_PORT
        value: "6379"

  - type: pserv
    name: pos-pc-db
    ipAddress: private
    dbName: pos_pc
    user: postgres
    postgresMajorVersion: 15

  - type: redis
    name: pos-pc-redis
    ipAddress: private
